const fs = require('fs');
const vm = require('vm');
const code = fs.readFileSync('game.js','utf8') + `\n;globalThis.__dbg={getState:()=>state, db:{BAND_DATABASE,BAND_LORE_DATABASE}, fns:{startNewGameInSlot,render,renderBandBookScreen,renderBandBookDetail,bandEntry,bandFlags,normalizeBandSystemState}};`;
function makeEl(){return{innerHTML:'',value:'',checked:false,dataset:{},style:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},addEventListener(){},removeEventListener(){},appendChild(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},click(){},closest(){return null},scrollLeft:0,offsetLeft:0,clientWidth:360};}
const app=makeEl();
const store=new Map();
const sb={console,document:{getElementById:(id)=>id==='app'?app:makeEl(),querySelector:()=>null,querySelectorAll:()=>[],createElement:()=>makeEl(),body:makeEl()},localStorage:{getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},navigator:{serviceWorker:null},location:{reload(){}},setTimeout:(fn)=>{ return 1;},clearTimeout(){},requestAnimationFrame:(fn)=>{try{fn()}catch(e){}},alert(){},confirm:()=>true,prompt:()=>null,Date,Math,JSON,Object,Array,Number,String,Boolean,RegExp,Set,Map,Promise,Error};
sb.window=sb; sb.globalThis=sb;
vm.createContext(sb); vm.runInContext(code,sb,{filename:'game.js'});
const d=sb.__dbg, F=d.fns;
function ok(c,msg){ if(!c){ console.error('[NG]',msg); process.exitCode=1; } else console.log('[OK]',msg); }
F.startNewGameInSlot(1);
let state=d.getState();
state.introSeen=true;
state.activePopup=null; state.popupQueue=[]; state.tutorialStage='done';
const bandIds=Object.keys(d.db.BAND_DATABASE);
const loreIds=Object.keys(d.db.BAND_LORE_DATABASE);
ok(bandIds.length===22,'BAND_DATABASE remains 22 bands');
ok(loreIds.length===bandIds.length,'BAND_LORE_DATABASE has records for every band');
ok(bandIds.every(id=>!!d.db.BAND_LORE_DATABASE[id]),'no missing lore record for existing band');
const loreItems=Object.values(d.db.BAND_LORE_DATABASE).flatMap(x=>x.lore||[]);
ok(loreItems.length===16,'priority 8 bands have 16 lore entries total');
ok(loreItems.every(item=>item.id && item.title && item.text),'every lore entry has id/title/text');
state.bandBookDetail='triple_arrows'; state.view='bandbook';
state.bandBook.bands.triple_arrows={state:'met', battleCount:1, firstMetTurn:5};
state.rivalRelations.triple_arrows=30;
state.bandBookDetailTab='comment';
F.render();
let html=app.innerHTML;
ok(html.includes('bandbook-tabs'),'detail screen renders tab UI');
ok(html.includes('代表者コメント'),'comment tab title rendered');
ok(html.includes('タカナシ'),'unlocked comment text rendered');
state.bandBookDetailTab='lore';
F.render();
html=app.innerHTML;
ok(html.includes('UNDERの常連席'),'relation 30 unlocks first lore');
ok(html.includes('未解放：交流60+'),'relation 30 keeps second lore locked');
state.rivalRelations.triple_arrows=60;
F.render();
html=app.innerHTML;
ok(html.includes('3本の矢の意味'),'relation 60 unlocks second lore');
state.bandBookDetail='kodama'; state.bandBookDetailTab='lore'; state.bandBook.bands.kodama={state:'met', battleCount:1, firstMetTurn:6}; state.rivalRelations.kodama=60;
F.render();
html=app.innerHTML;
ok(html.includes('今後追加予定'),'band with no lore shows placeholder rather than breaking');
console.log('AUDIT40D BANDBOOK LORE SMOKE PASSED');
