const fs = require('fs');
const vm = require('vm');
const code = fs.readFileSync('game.js','utf8') + `\n;globalThis.__dbg={getState:()=>state, fns:{startNewGameInSlot,render,renderSnsScreen,renderMailScreen,addMail,addSnsPostOnce,maybeSeedWorldReactionPosts,addLiveWorldReactionPosts,stripEphemeralState,hasUnsafeEphemeralStateForSave}};`;
function makeEl(){return{innerHTML:'',value:'',checked:false,dataset:{},style:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},addEventListener(){},removeEventListener(){},appendChild(){},querySelector(){return null},querySelectorAll(){return[]},focus(){},click(){},closest(){return null},scrollLeft:0,offsetLeft:0,clientWidth:360};}
const app=makeEl();
const store=new Map();
const sb={console,document:{getElementById:(id)=>id==='app'?app:makeEl(),querySelector:()=>null,querySelectorAll:()=>[],createElement:()=>makeEl(),body:makeEl()},localStorage:{getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},navigator:{serviceWorker:null},location:{reload(){}},setTimeout:(fn)=>{ return 1;},clearTimeout(){},requestAnimationFrame:(fn)=>{try{fn()}catch(e){}},alert(){},confirm:()=>true,prompt:()=>null,Date,Math,JSON,Object,Array,Number,String,Boolean,RegExp,Set,Map,Promise,Error};
sb.window=sb; sb.globalThis=sb;
vm.createContext(sb); vm.runInContext(code,sb,{filename:'game.js'});
const d=sb.__dbg, F=d.fns;
function ok(c,msg){ if(!c){ console.error('[NG]',msg); process.exitCode=1; } else console.log('[OK]',msg); }
F.startNewGameInSlot(1);
let state=d.getState();
state.introSeen=true; state.activePopup=null; state.popupQueue=[]; state.tutorialStage='done'; state.band.name='テストバンド'; state.view='home';
F.render();
ok(app.innerHTML.includes('goal-pulse-card'),'home renders strengthened goal pulse card');
ok(app.innerHTML.includes('UNDER FES'),'goal card references current target');
state.view='phone'; state.phoneSubView='mail';
F.addMail('出演依頼テスト','次のライブに出ませんか？','live_offer',{sender:'SHELTER受付'});
F.render();
ok(app.innerHTML.includes('mail-row-enhanced'),'mail rows use enhanced layout');
ok(app.innerHTML.includes('mail-sender-icon'),'mail sender icon rendered');
ok(app.innerHTML.includes('mail-kind-chip'),'mail kind chip rendered');
state.phoneSubView='sns'; state.snsPosts=[]; state.turn=44; state.snsWorldSeen={};
F.maybeSeedWorldReactionPosts();
ok(state.snsPosts.some(p=>p.author==='@fes_watch' && /LACT/.test(p.body)),'GRAND/Lact world SNS seeded');
ok(state.snsPosts.some(p=>p.author==='@underground_digest'),'GRAND countdown world SNS seeded');
const countAfterFirst=state.snsPosts.length;
F.maybeSeedWorldReactionPosts();
ok(state.snsPosts.length===countAfterFirst,'world SNS seed is once-per-key');
F.render();
ok(app.innerHTML.includes('sns-spotlight lact'),'SNS spotlight switches to LACT/GRAND tone');
state.snsPosts=[]; state.snsWorldSeen={}; state.turn=50; state.band.name='テストバンド';
F.addLiveWorldReactionPosts({rank:'A',liveEventId:'grand_test'},[{title:'夜明け前'}],{id:'grand_event',label:'GRAND UNDER FES',invitedBandIds:['triple_arrows'],liveType:'booking_band'});
ok(state.snsPosts.some(p=>p.author==='@listener_random'),'high-rank live reaction SNS added');
ok(state.snsPosts.some(p=>p.author==='@triple_arrows'),'invited band voice SNS added');
ok(state.snsPosts.some(p=>p.author==='@fes_watch' && /LACT/.test(p.body)),'GRAND live adds LACT sleeve reaction');
state.bandNamePrompt=false; state.activePopup=null; state.popupQueue=[];
ok(!F.hasUnsafeEphemeralStateForSave(true),'world reaction additions do not create unsafe ephemeral state');
const stripped=F.stripEphemeralState(state);
ok(stripped.snsWorldSeen && typeof stripped.snsWorldSeen==='object','snsWorldSeen persists as normal save data');
console.log('AUDIT40E WORLD REACTIONS SMOKE PASSED');
